image: Build and Deploy Code

pipelines:
  default:
    - step:
        name: Build and test
        script:
          - npm install
          - npm test
  branches:
    staging:
      - step:
          name: Hello
          script:
            - echo "Hello from Rushflow"