"""create data on tables

Revision ID: a26af631f1969
Revises: 
Create Date: 2022-10-20 12:40:47.209451

"""
import datetime
from alembic import op

from app.models.database.mentor.db_mentor_user import DB_Mentor_Users
from app.models.database.mentor.db_mentor_review import DB_Mentor_Review
from app.models.database.mentor.db_mentor_banners import DB_Mentor_Banners
from app.models.database.client.db_client_user import DB_Client_Users
from app.models.database.client.db_client_banners import DB_Client_Banners
from app.models.database.client.db_client_points import DB_Client_Points
from app.models.database.mentor.db_mentor_points import DB_Mentor_Points

from app.models.database.db_country import DB_Countries
from app.models.database.db_category import DB_Categories
from app.models.database.db_notifications import DB_Notifications
from app.models.database.db_majors import DB_Majors
from app.models.database.db_discount import DB_Discount
from app.models.database.db_appointment import DB_Appointments, AppointmentsState, AppointmentsType
from app.models.database.db_suffix import DB_Suffix
from app.models.database.db_payments import DB_Mentor_Payments, PaymentStatus, DB_Mentor_PaymentsـReports
from app.models.database.db_archive import DB_Archive


from app.utils.database import engine
from app.models.database.client.db_client_user import Base

# revision identifiers, used by Alembic.
revision = 'a26af631f1969'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)

    op.bulk_insert(DB_Discount.__table__,
    [
        {
            "id" : 1,
            "code" : "abdo50",
            "percent_value" : 50,         
        },
        {
            "id" : 2,
            "code" : "abdo30",
            "percent_value" : 30,         
        },
        {
            "id" : 3,
            "code" : "abdo10",
            "percent_value" : 10,         
        },
        {
            "id" : 4,
            "code" : "abdo90",
            "percent_value" : 90,         
        },
        {
            "id" : 5,
            "code" : "abd100",
            "percent_value" : 100,         
        }
    ]
    )
    
    op.bulk_insert(DB_Countries.__table__,
    [
        {
            "id" : 1,
            "flag_image" : "bahrain.png",
            "name_english" : "Bahrain",         
            "name_arabic" : "البحرين",   
            "currency_arabic" : "د.ب",
            "currency_english" : "BD",        
            "dialCode" : "00973",
            "minLength" : 8,
            "maxLength": 8
        },
        {          
            "id" : 2,
            "flag_image" : "egypt.png",
            "name_english" : "Eqypt",         
            "name_arabic" : "مصر",     
            "currency_arabic" : "ج.م",
            "currency_english" : "EGP",        
            "dialCode" : "0020",
            "minLength" : 10,
            "maxLength": 10
        }, 
        {
            "id" : 3,
            "flag_image" : "iraq.png",
            "name_english" : "Iraq",         
            "name_arabic" : "العراق",  
            "currency_arabic" : "د.ع",
            "currency_english" : "IQD",        
            "dialCode" : "00964",
            "minLength" : 10,
            "maxLength": 10
        }, 
        {
            "id" : 4,
            "flag_image" : "jordan.png",
            "name_english" : "Jordan",         
            "name_arabic" : "الاردن",         
            "currency_arabic" : "د.ا",   
            "currency_english" : "JD",        
            "dialCode" : "00962",
            "minLength" : 9,
            "maxLength": 9
        },
        {
            "id" : 5,
            "flag_image" : "kuwait.png",
            "name_english" : "Kuwait",         
            "name_arabic" : "الكويت",         
            "currency_arabic" : "د.ك",
            "currency_english" : "KWD",        
            "dialCode" : "00965",
            "minLength" : 8,
            "maxLength": 8
        },
        {
            "id" : 6,
            "flag_image" : "qatar.png",
            "name_english" : "Qatar",         
            "name_arabic" : "قطر",         
            "currency_arabic" : "ر.ق",
            "currency_english" : "QR",        
            "dialCode" : "00974",
            "minLength" : 8,
            "maxLength": 8
        }, 
        {
            "id" : 7,
            "flag_image" : "saudi.png",
            "name_english" : "Saudi Arabia",         
            "name_arabic" : "المملكة العربية السعودية",         
            "currency_arabic" : "ر.س",
            "currency_english" : "Riyal",        
            "dialCode" : "00966",
            "minLength" : 9,
            "maxLength": 9
        }, 
        {
            "id" : 8,
            "flag_image" : "emirates.png",
            "name_english" : "United Arab Emirates",         
            "name_arabic" : "الإمارات العربيّة المتّحدة",         
            "currency_arabic" : "د.إ",
            "currency_english" : "Dh",       
            "dialCode" : "00971",
            "minLength" : 9,
            "maxLength": 9
        },
        {
            "id" : 9,
            "flag_image" : "lebanon.png",
            "name_english" : "Lebanon",         
            "name_arabic" : "لبنان",         
            "currency_arabic" : "دولار",
            "currency_english" : "USD",       
            "dialCode" : "00961",
            "minLength" : 8,
            "maxLength": 8
        },
        {
            "id" : 10,
            "flag_image" : "palestine.png",
            "name_english" : "Palestinian Territory, Occupied",         
            "name_arabic" : "فلسطين المحتلة",         
            "currency_arabic" : "شيكل",
            "currency_english" : "₪",       
            "dialCode" : "00970",
            "minLength" : 9,
            "maxLength": 9
        }, 
        {
            "id" : 11,
            "flag_image" : "othercountry.png",
            "name_english" : "Other",         
            "name_arabic" : "اخرى",         
            "currency_arabic" : "دولار",     
            "currency_english" : "USD",        
            "dialCode" : "0000",
            "minLength" : 9,
            "maxLength": 9
        }
    ]
    )
    
    op.bulk_insert(DB_Suffix.__table__,
    [
         {
            "id" : 1,
            "name_english" : "Mr.",         
            "name_arabic" : "سيد .",         
        },
         {
            "id" : 2,
            "name_english" : "Mrs.",         
            "name_arabic" : "سيدة .",     
        },
         {
            "id" : 3,
            "name_english" : "Dr.",         
            "name_arabic" : "د .",     
        },
         {
            "id" : 4,
            "name_english" : "Eng.",         
            "name_arabic" : "م .",     
        },
        {
            "id" : 5,
            "name_english" : "Ph.",         
            "name_arabic" : "ب .",     
        },
    ]
    )
        
    op.bulk_insert(DB_Categories.__table__,
    [
         {
            "id" : 1,
            "name_english" : "Family",         
            "name_arabic" : "عائلي",              
            "icon" : "family.png"
        },
         {
            "id" : 2,
            "name_english" : "Employment",         
            "name_arabic" : "توظيف",              
            "icon" : "employment.png"
        },
         {
            "id" : 3,
            "name_english" : "Criminal Defense",         
            "name_arabic" : "الجنائي",              
            "icon" : "criminal.png"
        },
         {
            "id" : 4,
            "name_english" : "Real Estate",         
            "name_arabic" : "العقارات",               
            "icon" : "estate.png"
        },
         {
            "id" : 5,
            "name_english" : "Business",         
            "name_arabic" : "اعمال",               
            "icon" : "business.png"
        },
         {
            "id" : 6,
            "name_english" : "Immigration",         
            "name_arabic" : "هجره",           
            "icon" : "immigration.png"
        },
         {
            "id" : 7,
            "name_english" : "Personal Injury",         
            "name_arabic" : "إصابة شخصية",              
            "icon" : "injury.png"
        },
         {
            "id" : 8,
            "name_english" : "Wills, Trusts & Estates",         
            "name_arabic" : "الوصايا والصناديق الاستئمانية والعقارات",              
            "icon" : "wills.png"
        },
         {
            "id" : 9,
            "name_english" : "Bankruptcy & Finances",         
            "name_arabic" : "الإفلاس والمالية",              
            "icon" : "bankruptcy.png"
        },
         {
            "id" : 10,
            "name_english" : "Government",         
            "name_arabic" : "حكومة",              
            "icon" : "government.png"
        },
         {
            "id" : 11,
            "name_english" : "Products & Services",         
            "name_arabic" : "المنتجات والخدمات",              
            "icon" : "products.png"
        },
         {
            "id" : 12,
            "name_english" : "Intellectual Property",         
            "name_arabic" : "الملكية الفكرية",              
            "icon" : "intellectual.png"
        },
         {
            "id" : 13,
            "name_english" : "Insurance Law",         
            "name_arabic" : "قانون التأمين",              
            "icon" : "insurance.png"
        }
    ]
    )
    
    op.bulk_insert(DB_Majors.__table__,
    [
        {
            "id" : 1,
            "categories_id" : 1,
            "name_english" : "Adoptions",
            "name_arabic" : "التبني",         
        },
        {
            "id" : 2,
            "categories_id" : 1,
            "name_english" : "Child Custody and Visitation",
            "name_arabic" : "حضانة الطفل وزيارته",         
        },
        {
            "id" : 3,
            "categories_id" : 1,
            "name_english" : "Child Support",
            "name_arabic" : "دعم الطفل",         
        },
        {
            "id" : 4,
            "categories_id" : 1,
            "name_english" : "Divorce",
            "name_arabic" : "الطلاق",         
        },
        {
            "id" : 5,
            "categories_id" : 1,
            "name_english" : "Guardianship",
            "name_arabic" : "الوصاية",         
        },
        {
            "id" : 6,
            "categories_id" : 1,
            "name_english" : "Paternity",
            "name_arabic" : "أبوة",         
        },
        {
            "id" : 7,
            "categories_id" : 1,
            "name_english" : "Separations",
            "name_arabic" : "الفواصل",         
        },
        {
            "id" : 8,
            "categories_id" : 1,
            "name_english" : "Spousal Support or Alimony",
            "name_arabic" : "النفقة الزوجية",         
        },
        {
            "id" : 9,
            "categories_id" : 2,
            "name_english" : "Disabilities",
            "name_arabic" : "الإعاقات",         
        },
        {
            "id" : 10,
            "categories_id" : 2,
            "name_english" : "Employment Contracts",
            "name_arabic" : "عقود توظيف",         
        },
        {
            "id" : 11,
            "categories_id" : 2,
            "name_english" : "Employment Discrimination",
            "name_arabic" : "التمييز في العمل",         
        },
        {
            "id" : 12,
            "categories_id" : 2,
            "name_english" : "Pensions and Benefits",
            "name_arabic" : "المعاشات التقاعدية والفوائد",         
        },
        {
            "id" : 13,
            "categories_id" : 2,
            "name_english" : "Sexual Harassment",
            "name_arabic" : "التحرش الجنسي",         
        },
        {
            "id" : 14,
            "categories_id" : 2,
            "name_english" : "Wages and Overtime Pay",
            "name_arabic" : "الأجور وأجور العمل الإضافي",         
        },
        {
            "id" : 15,
            "categories_id" : 2,
            "name_english" : "Workplace Disputes",
            "name_arabic" : "النزاعات في مكان العمل",         
        },
        {
            "id" : 16,
            "categories_id" : 2,
            "name_english" : "Wrongful Termination",
            "name_arabic" : "إنهاء غير مشروع",         
        },
        {
            "id" : 17,
            "categories_id" : 3,
            "name_english" : "Criminal Law",
            "name_arabic" : "قانون جنائي",         
        },
        {
            "id" : 18,
            "categories_id" : 3,
            "name_english" : "Drug Crimes",
            "name_arabic" : "جرائم المخدرات",         
        },
        {
            "id" : 19,
            "categories_id" : 3,
            "name_english" : "Misdemeanors",
            "name_arabic" : "الجنح",         
        },
        {
            "id" : 20,
            "categories_id" : 3,
            "name_english" : "Theft",
            "name_arabic" : "سرقة",         
        },
        {
            "id" : 21,
            "categories_id" : 3,
            "name_english" : "Drunk Driving",
            "name_arabic" : "قياده تحت تاثير الخمر",         
        },
        {
            "id" : 22,
            "categories_id" : 3,
            "name_english" : "Speeding and Moving Violations",
            "name_arabic" : "مخالفات السرعة والتحرك",         
        },
        {
            "id" : 23,
            "categories_id" : 3,
            "name_english" : "Felonies",
            "name_arabic" : "الجنايات",         
        },
        {
            "id" : 24,
            "categories_id" : 3,
            "name_english" : "White Collar Crime",
            "name_arabic" : "جريمة رجال الأعمال",         
        },
        {
            "id" : 25,
            "categories_id" : 4,
            "name_english" : "Condominiums and Cooperatives",
            "name_arabic" : "الوحدات السكنية والتعاونيات",         
        },    
        {
            "id" : 26,
            "categories_id" : 4,
            "name_english" : "Construction Disputes",
            "name_arabic" : "منازعات البناء",         
        }, 
        {
            "id" : 27,
            "categories_id" : 4,
            "name_english" : "Foreclosures",
            "name_arabic" : "حبس الرهن",         
        },
        {
            "id" : 28,
            "categories_id" : 4,
            "name_english" : "Landlord and Tenant",
            "name_arabic" : "المالك والمستأجر",         
        },
        {
            "id" : 29,
            "categories_id" : 4,
            "name_english" : "Mortgages",
            "name_arabic" : "الرهون العقارية",         
        },
        {
            "id" : 30,
            "categories_id" : 4,
            "name_english" : "Purchase and Sale of Residence",
            "name_arabic" : "شراء وبيع العقار",         
        },
        {
            "id" : 31,
            "categories_id" : 4,
            "name_english" : "Title and Boundary Disputes",
            "name_arabic" : "نزاعات الملكية والحدود",         
        },
        {
            "id" : 32,
            "categories_id" : 4,
            "name_english" : "Zoning, Planning and Land Use",
            "name_arabic" : "التقسيم والتخطيط واستخدام الأراضي",         
        },
        {
            "id" : 33,
            "categories_id" : 5,
            "name_english" : "Breach of Contract",
            "name_arabic" : "خرق العقد",         
        },
        {
            "id" : 34,
            "categories_id" : 5,
            "name_english" : "Business Disputes",
            "name_arabic" : "النزاعات التجارية",         
        },
        {
            "id" : 35,
            "categories_id" : 5,
            "name_english" : "Buying and Selling a Business",
            "name_arabic" : "بيع وشراء الأعمال",         
        },
        {
            "id" : 36,
            "categories_id" : 5,
            "name_english" : "Contract Drafting and Review",
            "name_arabic" : "صياغة العقد ومراجعته",         
        },
        {
            "id" : 37,
            "categories_id" : 5,
            "name_english" : "Corps, LLCs, Partnerships, etc.",
            "name_arabic" : "الشركات ذات المسؤولية المحدودة، الشراكات",         
        },
        {
            "id" : 38,
            "categories_id" : 5,
            "name_english" : "Entertainment Law",
            "name_arabic" : "قانون الترفيه",         
        },
        {
            "id" : 39,
            "categories_id" : 6,
            "name_english" : "Citizenship",
            "name_arabic" : "المواطنة",         
        },
        {
            "id" : 40,
            "categories_id" : 6,
            "name_english" : "Permanent Visas",
            "name_arabic" : "تأشيرات دائمة",         
        },
        {
            "id" : 41,
            "categories_id" : 6,
            "name_english" : "Removal or Deportation",
            "name_arabic" : "الإبعاد أو الترحيل",         
        },
        {
            "id" : 42,
            "categories_id" : 6,
            "name_english" : "Temporary Visas",
            "name_arabic" : "تأشيرات مؤقتة",         
        },
        {
            "id" : 43,
            "categories_id" : 7,
            "name_english" : "Automobile Accidents",
            "name_arabic" : "حوادث السيارات",         
        },
        {
            "id" : 44,
            "categories_id" : 7,
            "name_english" : "Dangerous Property/Buildings",
            "name_arabic" : "الممتلكات / المباني الخطرة",         
        },
        {
            "id" : 45,
            "categories_id" : 7,
            "name_english" : "Defective Products",
            "name_arabic" : "المنتجات المعيبة",         
        },
        {
            "id" : 46,
            "categories_id" : 7,
            "name_english" : "Medical Malpractice",
            "name_arabic" : "الأخطاء الطبية",         
        },
        {
            "id" : 47,
            "categories_id" : 7,
            "name_english" : "Wrongful Death",
            "name_arabic" : "القتل الخطأ",         
        },
        {
            "id" : 48,
            "categories_id" : 7,
            "name_english" : "Personal Injury",
            "name_arabic" : "إصابة شخصية",         
        },
        {
            "id" : 49,
            "categories_id" : 8,
            "name_english" : "Contested Wills or Probate",
            "name_arabic" : "الوصايا المتنازع عليها أو الوصية",         
        },
        {
            "id" : 50,
            "categories_id" : 8,
            "name_english" : "Drafting Wills and Trusts",
            "name_arabic" : "صياغة الوصايا والصناديق الاستئمانية",         
        },
        {
            "id" : 51,
            "categories_id" : 8,
            "name_english" : "Estate Administration",
            "name_arabic" : "إدارة العقارات",         
        },
        {
            "id" : 52,
            "categories_id" : 8,
            "name_english" : "Estate Planning",
            "name_arabic" : "التخطيط العقاري",         
        },
        {
            "id" : 53,
            "categories_id" : 9,
            "name_english" : "Business Bankruptcy",
            "name_arabic" : "إفلاس الأعمال",         
        },
        {
            "id" : 54,
            "categories_id" : 9,
            "name_english" : "Consumer Bankruptcy",
            "name_arabic" : "إفلاس المستهلك",         
        },
        {
            "id" : 55,
            "categories_id" : 10,
            "name_english" : "Education and Schools",
            "name_arabic" : "التعليم والمدارس",         
        },
        {
            "id" : 56,
            "categories_id" : 10,
            "name_english" : "Government Agencies/Programs",
            "name_arabic" : "الوكالات/البرامج الحكومية",         
        },
        {
            "id" : 57,
            "categories_id" : 10,
            "name_english" : "Government Discrimination",
            "name_arabic" : "التمييز الحكومي",         
        },
        {
            "id" : 58,
            "categories_id" : 10,
            "name_english" : "Social Security - Disability",
            "name_arabic" : "الضمان الاجتماعي - الإعاقة",         
        },
        {
            "id" : 59,
            "categories_id" : 10,
            "name_english" : "Social Security - Retirement",
            "name_arabic" : "الضمان الاجتماعي - التقاعد",         
        },
        {
            "id" : 60,
            "categories_id" : 10,
            "name_english" : "Veterans Benefits",
            "name_arabic" : "فوائد المحاربين القدامى",         
        },
        {
            "id" : 61,
            "categories_id" : 11,
            "name_english" : "Attorney Malpractice",
            "name_arabic" : "سوء ممارسة المحامي",         
        },
        {
            "id" : 62,
            "categories_id" : 11,
            "name_english" : "Defective Products",
            "name_arabic" : "المنتجات المعيبة",         
        },
        {
            "id" : 63,
            "categories_id" : 11,
            "name_english" : "Drugs and Medical Devices",
            "name_arabic" : "الأدوية والأجهزة الطبية",         
        },
        {
            "id" : 64,
            "categories_id" : 11,
            "name_english" : "Product Liability/Replacement",
            "name_arabic" : "المسؤولية عن المنتج/الاستبدال",         
        },
        {
            "id" : 65,
            "categories_id" : 11,
            "name_english" : "Warranties",
            "name_arabic" : "الضمانات",         
        },
        {
            "id" : 66,
            "categories_id" : 12,
            "name_english" : "Copyright",
            "name_arabic" : "حقوق النشر",         
        },
        {
            "id" : 67,
            "categories_id" : 12,
            "name_english" : "Intellectual Property",
            "name_arabic" : "الملكية الفكرية",         
        },
        {
            "id" : 68,
            "categories_id" : 12,
            "name_english" : "Patents",
            "name_arabic" : "براءات الاختراع",         
        },
        {
            "id" : 69,
            "categories_id" : 12,
            "name_english" : "Trade Secrets",
            "name_arabic" : "الأسرار التجارية",         
        },
        {
            "id" : 70,
            "categories_id" : 12,
            "name_english" : "Trademarks",
            "name_arabic" : "العلامات التجارية",         
        },
        {
            "id" : 71,
            "categories_id" : 13,
            "name_english" : "Annuities",
            "name_arabic" : "المعاشات",         
        },
        {
            "id" : 72,
            "categories_id" : 13,
            "name_english" : "Automobile Insurance Claims",
            "name_arabic" : "مطالبات التأمين على السيارات",         
        },
        {
            "id" : 73,
            "categories_id" : 13,
            "name_english" : "Commercial Insurance",
            "name_arabic" : "التأمين التجاري",         
        },
        {
            "id" : 74,
            "categories_id" : 13,
            "name_english" : "Health Insurance",
            "name_arabic" : "تأمين صحي",         
        },
        {
            "id" : 75,
            "categories_id" : 13,
            "name_english" : "Life Insurance",
            "name_arabic" : "التأمين على الحياة",         
        },
        {
            "id" : 76,
            "categories_id" : 13,
            "name_english" : "Property Insurance",
            "name_arabic" : "تأمين الملكية",         
        }
    ]
    )

    op.bulk_insert(DB_Client_Users.__table__,
    [
        {
            "id" : 1,
            "first_name" : "abed alrahman",
            "last_name" : "al haj hussain",         
            "mobile_number" : "00962795190663",        
            "email" : "aboud.masoud.92@gmail.com",         
            "gender" : 1,  
            "allow_notifications" : True,
            "blocked" : False,
            "invitation_code" : "123456",
            "profile_img" : "",
            "os_type" : "iOS",         
            "device_type_name" : "iPhone XR",        
            "os_version" : "16.2",         
            "app_version" : "1.0",
            "date_of_birth" : "1992/05/22",         
            "last_otp" : "0000",      
            "push_token" : "",         
            "country_id" : 4,
            "api_key" : "00101",
        },
        {
            "id" : 2,
            "first_name" : "mohammed",
            "last_name" : "maswadeh",         
            "mobile_number" : "00962795190661",        
            "email" : "aboud.masoud.91@gmail.com",         
            "gender" : 2,              
            "allow_notifications" : True,         
            "blocked" : True,         
            "invitation_code" : "234567",
            "profile_img" : "",
            "os_type" : "iOS",         
            "device_type_name" : "iPhone XR",        
            "os_version" : "16.2",         
            "app_version" : "1.0",         
            "date_of_birth" : "1992/05/22",         
            "last_otp" : "0000",         
            "api_key" : "00102",
            "push_token" : "",         
            "country_id" : 4
        }
    ]
    )
            
    op.bulk_insert(DB_Mentor_Users.__table__,
    [
        {
            "id" : 1,
            "category_id" : 1,
            "suffixe_name" : "Sr.",
            "first_name" : "abed alrahman 1",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 0],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "00962790000001",
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",
            "email" : "aboud.masoud.1@gmail.com",
            "gender" : 1,
            "hour_rate" : 20.5,   
            "invitation_code" : "123",
            "profile_img" : "1.png",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",   
            "experience_since" : "1992",
            "api_key" : "00001",
            "push_token" : "",    
            "country_id" : 6
        },
        {
            "id" : 2,
            "suffixe_name" : "Dr.",
            "first_name" : "abed alrahman 2",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",          
            "speaking_language" : ["English", "العربية"],  
            "majors" : [1, 2, 3, 4, 5, 6, 7, 19, 18, 15, 17, 16, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "00962790000002",
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",        
            "email" : "aboud.masoud.2@gmail.com",
            "category_id" : 1,  
            "gender" : 2,  
            "hour_rate" : 34.7,                
            "invitation_code" : "234",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",   
            "experience_since" : "1999",
            "api_key" : "00002",
            "push_token" : "",         
            "country_id" : 2
        },        
        {
            "id" : 3,
            "suffixe_name" : "Dr.",
            "first_name" : "abed alrahman 3",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],            
            "majors" : [21, 22, 20, 24, 23, 6, 7, 19, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "00962790000003",
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",        
            "email" : "aboud.masoud.3@gmail.com",
            "category_id" : 2,
            "hour_rate" : 12.1,                  
            "gender" : 0,         
            "invitation_code" : "345",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2000",
            "api_key" : "00003", 
            "push_token" : "",        
            "country_id" : 7
        },
        {
            "id" : 4,
            "suffixe_name" : "Mr.",
            "first_name" : "abed alrahman 4",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "00962790000004",   
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",             
            "email" : "aboud.masoud.4@gmail.com",
            "category_id" : 1,
            "hour_rate" : 65.0,                    
            "gender" : 0,         
            "invitation_code" : "456",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2014",                        
            "api_key" : "00004",
            "push_token" : "",         
            "country_id" : 6
        },
        {
            "id" : 5,
            "suffixe_name" : "Mrs.",
            "first_name" : "abed alrahman 5",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "00962790000005",
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",                
            "email" : "aboud.masoud.5@gmail.com",
            "category_id" : 3,
            "hour_rate" : 33.0,                      
            "gender" : 0,         
            "invitation_code" : "567",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2014",                                 
            "api_key" : "00005",
            "push_token" : "",         
            "country_id" : 1
        },
        {
            "id" : 6,
            "suffixe_name" : "Mrs.",
            "first_name" : "abed alrahman 6",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية", 
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "00962790000006",
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",                
            "email" : "aboud.masoud.6@gmail.com",
            "category_id" : 2,  
            "gender" : 0,
            "hour_rate" : 17.8,                               
            "invitation_code" : "678",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2014",                                 
            "api_key" : "00006",
            "push_token" : "",         
            "country_id" : 5
        },
        {
            "id" : 7,
            "suffixe_name" : "Mr.",
            "first_name" : "abed alrahman 7",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "00962790000007", 
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",               
            "email" : "aboud.masoud.7@gmail.com",
            "category_id" : 2,  
            "gender" : 0,
            "hour_rate" : 43.0,                                        
            "invitation_code" : "789",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2014",                              
            "api_key" : "00007",
            "push_token" : "",         
            "country_id" : 6
        },
        {
            "id" : 8,
            "suffixe_name" : "Sr.",
            "first_name" : "abed alrahman 8",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 21],
            "mobile_number" : "00962790000008", 
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",               
            "email" : "aboud.masoud.8@gmail.com",
            "category_id" : 2,
            "hour_rate" : 77.2,                                          
            "gender" : 0,         
            "invitation_code" : "890",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2019",                                       
            "api_key" : "00008",
            "push_token" : "",        
            "country_id" : 5
        },
        {
            "id" : 9,
            "suffixe_name" : "Dr.",
            "first_name" : "abed alrahman 9",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "00962790000009",   
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",             
            "email" : "aboud.masoud.9@gmail.com",
            "category_id" : 4,
            "hour_rate" : 12.2,                                            
            "gender" : 0,         
            "invitation_code" : "901",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2020",                                                
            "api_key" : "00009",
            "push_token" : "",        
            "country_id" : 5
        },
        {
            "id" : 10,
            "suffixe_name" : "Dr.",
            "first_name" : "abed alrahman 10",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "009627900000010", 
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",               
            "email" : "aboud.masoud.10@gmail.com",
            "category_id" : 3,
            "hour_rate" : 28.9,                                              
            "gender" : 0,         
            "invitation_code" : "012",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2000",                                                         
            "api_key" : "000010",
            "push_token" : "",         
            "country_id" : 4
        },
        {
            "id" : 11,
            "suffixe_name" : "Dr.",
            "first_name" : "abed alrahman 11",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "009627900000011",   
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",             
            "email" : "aboud.masoud.11@gmail.com",
            "category_id" : 7,  
            "gender" : 0,
            "hour_rate" : 35.2,                                                       
            "invitation_code" : "098",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2000",                                                                  
            "api_key" : "000011",
            "push_token" : "",         
            "country_id" : 3
        },
        {
            "id" : 12,
            "suffixe_name" : "Dr.",
            "first_name" : "abed alrahman 12",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "009627900000012", 
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",               
            "email" : "aboud.masoud.12@gmail.com",
            "category_id" : 2,  
            "gender" : 0,
            "hour_rate" : 52.1,                                                                
            "invitation_code" : "987",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2001",                                                                  
            "api_key" : "000012",
            "push_token" : "",         
            "country_id" : 2
        },
        {
            "id" : 13,
            "suffixe_name" : "Dr.",
            "first_name" : "abed alrahman 13",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "009627900000013",  
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",              
            "email" : "aboud.masoud.13@gmail.com",
            "category_id" : 7,  
            "gender" : 0,  
            "hour_rate" : 11.0,                           
            "invitation_code" : "876",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2011",                                                                           
            "api_key" : "000013",
            "push_token" : "",         
            "country_id" : 3
        },
        {
            "id" : 14,
            "suffixe_name" : "Mr.",
            "first_name" : "abed alrahman 14",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "009627900000014", 
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",               
            "email" : "aboud.masoud.14@gmail.com",
            "category_id" : 2,  
            "gender" : 0,
            "hour_rate" : 14.0,                    
            "invitation_code" : "765",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2020",                                                                                    
            "api_key" : "000014",
            "push_token" : "",         
            "country_id" : 2
        },
        {
            "id" : 15,
            "suffixe_name" : "Mr.",
            "first_name" : "abed alrahman 15",
            "last_name" : "al haj hussain",
            "bio" : "استشاري الأسرة و الصحة النفسية و علاج الإدمان حاصل على ٦ زمالات السعودية و العربية و الاستراليه و الامريكيه جامعتي هارفورد و كاليفورنيا اريفاين والاسترالية الطبيب الاردني الوحيد الحاصل على زمالة الصحة النفسية الاولية و رئيس برنامج زمالة الصحة النفسيه الاردنية",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 22, 20, 28, 23, 6, 7, 29, 25, 27, 17, 26, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "009627900000015",
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",                
            "email" : "aboud.masoud.15@gmail.com",
            "category_id" : 5,  
            "gender" : 0, 
            "hour_rate" : 84.0,                            
            "invitation_code" : "654",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "22/05/1992",
            "experience_since" : "2021",                                                                                             
            "api_key" : "000015",
            "push_token" : "",         
            "country_id" : 2
        },
        {
            "id" : 16,
            "suffixe_name" : "Mrs.",
            "first_name" : "sanaa",
            "last_name" : "salameh",
            "bio" : "I am Hr officer and administrative professional with over five years experience in the education sector . My specialty lies in planning, management, presentation and more . looking for job.",
            "speaking_language" : ["English", "العربية"],
            "majors" : [30, 1, 20, 28, 23, 6, 7, 29, 2, 27, 17, 3, 14],
            "working_hours_saturday" : [1, 2, 3, 4, 6, 7],
            "working_hours_sunday" : [3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
            "working_hours_monday" : [4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23],
            "working_hours_tuesday" : [5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22, 23],
            "working_hours_wednesday" : [6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23],
            "working_hours_thursday" : [7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0],
            "working_hours_friday" : [8, 10, 11, 12, 13, 14, 15, 16, 17, 19, 0],
            "mobile_number" : "009627900000016",
            "password" : "$2b$12$BVdr8Xp/t4AiwvmaCRfaKuicRzK5ss08le5t52lOXdRs2ndAHxhke",                
            "email" : "aboud.masoud.16@gmail.com",
            "category_id" : 6,  
            "gender" : 1, 
            "hour_rate" : 120.0,                            
            "invitation_code" : "543",
            "profile_img" : "",
            "id_img" : "1.png",
            "cv" : "1.pdf",
            "cert1" : "1.pdf",
            "cert2" : "2.pdf",
            "cert3" : "3.pdf",
            "blocked" : False,
            "published" : True, 
            "app_version" : "1.0",         
            "date_of_birth" : "12/01/1990",
            "experience_since" : "2000",                                                                                             
            "api_key" : "000016",
            "push_token" : "",         
            "country_id" : 8
        }
    ]
    )
    
    op.bulk_insert(DB_Mentor_Points.__table__,
    [
        {
            "id" : 1,
            "mentor_id" : 2,
            "invited_mentor_id" : 1,
            "reason" : "Registration"
        }
    ]
    )
        
    op.bulk_insert(DB_Appointments.__table__,
    [
        {
            "id" : 1,
            "mentor_id" : 1,
            "client_id" : 1,
            "date_from" : datetime.datetime(2023, 12, 28, 8),
            "date_to" : datetime.datetime(2023, 12, 28, 9),
            "is_free" : False,
            "price" : 20,
            "discounted_price" : 10,
            "currency_english" : "JD",
            "currency_arabic" : "د.ا",
            "mentor_hour_rate" : 20,
            "appointment_type" : AppointmentsType.schudule,
            "state" : AppointmentsState.completed,
            "note_from_client" : "example Client note",
            "note_from_mentor" : "example mentor note",
            "channel_id" : "test1",
            "mentor_join_call" : datetime.datetime(2023, 12, 28, 8),
            "client_join_call" : datetime.datetime(2023, 12, 28, 8),
            "mentor_date_of_close" : datetime.datetime(2023, 12, 28, 9),
            "client_date_of_close" : datetime.datetime(2023, 12, 28, 9)
        },
        {
            "id" : 2,
            "mentor_id" : 15,            
            "client_id" : 2,
            "date_from" : datetime.datetime(2023, 12, 31, 14),    
            "date_to" : datetime.datetime(2023, 12, 31, 14, 30),
            "is_free" : False,
            "price" : 20,
            "discounted_price" : 10,
            "currency_english" : "JD",
            "currency_arabic" : "د.ا",
            "mentor_hour_rate" : 20,
            "appointment_type" : AppointmentsType.schudule,
            "state" : AppointmentsState.active,
            "note_from_client" : "this is Client note",
            "note_from_mentor" : None,
            "channel_id" : "test2",
            "mentor_join_call" : None,
            "client_join_call" : None,
            "mentor_date_of_close" : None,
            "client_date_of_close" : None
        },
        {
            "id" : 3,
            "mentor_id" : 2,
            "client_id" : 1,
            "date_from" : datetime.datetime(2023, 12, 31, 10),    
            "date_to" : datetime.datetime(2023, 12, 31, 10, 15),
            "is_free" : False,
            "price" : 20,
            "discounted_price" : 10,
            "currency_english" : "JD",
            "currency_arabic" : "د.ا",
            "mentor_hour_rate" : 20,
            "appointment_type" : AppointmentsType.instant,
            "state" : AppointmentsState.active,
            "note_from_client" : None,
            "note_from_mentor" : "this is mentor note",
            "channel_id" : "test3",
            "mentor_join_call" : None,
            "client_join_call" : None,
            "mentor_date_of_close" : None,
            "client_date_of_close" : None
        },
        {
            "id" : 4,
            "mentor_id" : 2,
            "client_id" : 1,
            "date_from" : datetime.datetime(2023, 12, 25, 0),    
            "date_to" : datetime.datetime(2023, 12, 25, 0, 30),
            "is_free" : False,
            "price" : 20,
            "discounted_price" : 10,
            "currency_english" : "JD",
            "currency_arabic" : "د.ا",
            "mentor_hour_rate" : 20,
            "appointment_type" : AppointmentsType.instant,
            "state" : AppointmentsState.completed,
            "note_from_client" : None,
            "note_from_mentor" : "this is mentor note",
            "channel_id" : "test4",
            "mentor_join_call" : datetime.datetime(2023, 12, 25, 0),
            "client_join_call" : datetime.datetime(2023, 12, 25, 0),
            "mentor_date_of_close" : datetime.datetime(2023, 12, 25, 0, 30),
            "client_date_of_close" : datetime.datetime(2023, 12, 25, 0, 30)
        },
        {
            "id" : 5,
            "mentor_id" : 2,
            "client_id" : 1,
            "date_from" : datetime.datetime(2023, 12, 26, 10),    
            "date_to" : datetime.datetime(2023, 12, 26, 10, 15),
            "is_free" : False,
            "price" : 20,
            "discounted_price" : 10,
            "currency_english" : "JD",
            "currency_arabic" : "د.ا",
            "mentor_hour_rate" : 20,
            "appointment_type" : AppointmentsType.instant,
            "state" : AppointmentsState.mentor_cancel,
            "note_from_client" : None,
            "note_from_mentor" : None,
            "channel_id" : "test5",
            "mentor_join_call" : None,
            "client_join_call" : None,
            "mentor_date_of_close" : None,
            "client_date_of_close" : None
        },
        {
            "id" : 6,
            "mentor_id" : 2,
            "client_id" : 2,
            "date_from" : datetime.datetime(2023, 12, 27, 19),    
            "date_to" : datetime.datetime(2023, 12, 27, 19, 30),
            "is_free" : False,
            "price" : 20,
            "discounted_price" : 10,
            "currency_english" : "JD",
            "currency_arabic" : "د.ا",
            "mentor_hour_rate" : 20,
            "appointment_type" : AppointmentsType.schudule,
            "state" : AppointmentsState.client_cancel,
            "note_from_client" : None,
            "note_from_mentor" : None,
            "channel_id" : "test6",
            "mentor_join_call" : None,
            "client_join_call" : None,
            "mentor_date_of_close" : None,
            "client_date_of_close" : None
        },
        {
            "id" : 7,
            "mentor_id" : 1,
            "client_id" : 1,
            "date_from" : datetime.datetime(2023, 12, 30, 20),    
            "date_to" : datetime.datetime(2023, 12, 30, 21),
            "is_free" : False,
            "price" : 20,
            "discounted_price" : 10,
            "currency_english" : "JD",
            "currency_arabic" : "د.ا",
            "mentor_hour_rate" : 20,
            "appointment_type" : AppointmentsType.schudule,
            "state" : AppointmentsState.active,
            "note_from_client" : None,
            "note_from_mentor" : None,
            "channel_id" : "test7",
            "mentor_join_call" : None,
            "client_join_call" : None,
            "mentor_date_of_close" : None,
            "client_date_of_close" : None
        },
        {
            "id" : 8,
            "mentor_id" : 4,
            "client_id" : 1,
            "date_from" : datetime.datetime(2023, 12, 30, 21),    
            "date_to" : datetime.datetime(2023, 12, 30, 22),
            "is_free" : False,
            "price" : 20,
            "discounted_price" : 10,
            "currency_english" : "JD",
            "currency_arabic" : "د.ا",
            "mentor_hour_rate" : 20,
            "appointment_type" : AppointmentsType.instant,
            "state" : AppointmentsState.active,
            "note_from_client" : "this is Client note",
            "note_from_mentor" : None,
            "channel_id" : "test8",
            "mentor_join_call" : None,
            "client_join_call" : None,
            "mentor_date_of_close" : None,
            "client_date_of_close" : None
        },
        {
            "id" : 9,
            "mentor_id" : 5,
            "client_id" : 1,
            "date_from" : datetime.datetime(2023, 12, 31, 14),    
            "date_to" : datetime.datetime(2023, 12, 31, 14, 15),
            "is_free" : False,
            "price" : 20,
            "discounted_price" : 10,
            "currency_english" : "JD",
            "currency_arabic" : "د.ا",
            "mentor_hour_rate" : 20,
            "appointment_type" : AppointmentsType.schudule,
            "state" : AppointmentsState.active,
            "note_from_client" : None,
            "note_from_mentor" : None,
            "channel_id" : "test9",
            "mentor_join_call" : None,
            "client_join_call" : None,
            "mentor_date_of_close" : None,
            "client_date_of_close" : None
        },
        {
            "id" : 10,
            "mentor_id" : 2,
            "client_id" : 1,
            "date_from" : datetime.datetime(2023, 12, 30, 15),    
            "date_to" : datetime.datetime(2023, 12, 30, 15, 15),
            "is_free" : False,
            "price" : 20,
            "discounted_price" : 10,
            "currency_english" : "JD",
            "currency_arabic" : "د.ا",
            "mentor_hour_rate" : 20,
            "appointment_type" : AppointmentsType.schudule,
            "state" : AppointmentsState.active,
            "note_from_client" : None,
            "note_from_mentor" : None,
            "channel_id" : "test10",
            "mentor_join_call" : None,
            "client_join_call" : None,
            "mentor_date_of_close" : None,
            "client_date_of_close" : None
        },
    ]
    )
    
    op.bulk_insert(DB_Mentor_Review.__table__,
    [
        {
            "id" : 1,
            "mentor_id" : 4,
            "client_id" : 1,         
            "stars" : 4.7,        
            "comment" : "nice 1"
        },
        {
            "id" : 2,
            "mentor_id" : 4,
            "client_id" : 2,         
            "stars" : 3.2,        
            "comment" : "nice 2"
        },
    ]
    )
    
    op.bulk_insert(DB_Archive.__table__,
    [
       
        {
            "id" : 1,
            "mentor_id" : 1,
            "client_id" : 1,
            "appointment_id" : 1,
            "attachment" : "32rcv2324f.mp4"
        },
        {
            "id" : 2,
            "mentor_id" : 1,            
            "client_id" : 2,
            "appointment_id" : 2,
            "attachment" : "234t32rf23fv.mp4"
        },
        {
            "id" : 3,
            "mentor_id" : 2,
            "client_id" : 1,
            "appointment_id" : 3,
            "attachment" : "326982364.mp4"
        },
    ]
    )
    
    op.bulk_insert(DB_Notifications.__table__,
    [
        {
            "id" : 1,
            "title_english" : "notification title 1",
            "title_arabic" : "تنبيه رقم ١",         
            "content_english" : "notification content 1",
            "content_arabic" : "محتوى التنبيه ١",          
            "client_owner_id" : 1,
            "mentor_owner_id" : None,
        },
        {
            "id" : 2,
            "title_english" : "notification title 2",
            "title_arabic" : "تنبيه رقم ٢",         
            "content_english" : "notification content 2",
            "content_arabic" : "محتوى التنبيه ٢",          
            "client_owner_id" : 1,
            "mentor_owner_id" : None,
        },
        {
            "id" : 3,
            "title_english" : "notification title 3",
            "title_arabic" : "تنبيه رقم 3",         
            "content_english" : "notification content 3",
            "content_arabic" : "محتوى التنبيه 3",    
            "client_owner_id" : None,      
            "mentor_owner_id" : 1,
        },
        {
            "id" : 4,
            "title_english" : "notification title 4",
            "title_arabic" : "تنبيه رقم 4",         
            "content_english" : "notification content 4",
            "content_arabic" : "محتوى التنبيه 4",    
            "client_owner_id" : None,      
            "mentor_owner_id" : 1,
        }          
    ]
    )
    
    op.bulk_insert(DB_Mentor_Banners.__table__,
    [
        {
            "id" : 1,      
            "language" : "en",
            "image" : "banner1.png",
            "published" : True      
        },
        {
            "id" : 2,      
            "language" : "en",
            "image" : "banner2.jpg",
            "action_type" : "https://www.youtube.com/watch?v=FrCO41i2tWM&ab_channel=%D8%AD%D8%B3%D9%86%D8%A7%D9%84%D9%81%D8%A7%D8%B6%D9%84%D9%8A-ElfadiliTV",
            "published" : True         
        },
        {
            "id" : 3,      
            "language" : "ar",
            "image" : "banner3.jpg",
            "published" : True            
        },
        {
            "id" : 4,      
            "language" : "ar",
            "image" : "banner4.png",
            "published" : True           
        },
        {
            "id" : 5,      
            "language" : "ar",
            "image" : "banner5.png",
            "published" : True           
        },
        {
            "id" : 6,      
            "language" : "en",
            "image" : "banner6.png",
            "published" : True           
        },
    ]
    )
    
    op.bulk_insert(DB_Client_Banners.__table__,
    [
        {
            "id" : 1,      
            "language" : "en",
            "image" : "banner1.png",
            "published" : True      
        },
        {
            "id" : 2,      
            "language" : "en",
            "image" : "banner2.jpg",
            "action_type" : "https://www.youtube.com/watch?v=FrCO41i2tWM&ab_channel=%D8%AD%D8%B3%D9%86%D8%A7%D9%84%D9%81%D8%A7%D8%B6%D9%84%D9%8A-ElfadiliTV",
            "published" : True         
        },
        {
            "id" : 3,      
            "language" : "ar",
            "image" : "banner3.jpg",
            "published" : True            
        },
        {
            "id" : 4,      
            "language" : "ar",
            "image" : "banner4.png",
            "published" : True           
        },
        {
            "id" : 5,      
            "language" : "ar",
            "image" : "banner5.png",
            "published" : True           
        },
        {
            "id" : 6,      
            "language" : "en",
            "image" : "banner6.png",
            "published" : True           
        },
    ]
    )
    
    op.bulk_insert(DB_Mentor_Payments.__table__,
    [
        {
            "id" : 1,
            "mentor_id" : 1,
            "appointment_id" : 1,
            "status" : PaymentStatus.pending,   
            "amount" : 12,   
            "currency_arabic" : "د.ا",   
            "currency_english" : "JD",    
        },
        {
            "id" : 2,
            "mentor_id" : 2,
            "appointment_id" : 1,
            "status" : PaymentStatus.pending,   
            "amount" : 12,   
            "currency_arabic" : "د.ا",   
            "currency_english" : "JD",    
        },        
        {
            "id" : 3,
            "mentor_id" : 2,
            "appointment_id" : 3,
            "status" : PaymentStatus.pending,   
            "amount" : 19.2,   
            "currency_arabic" : "د.ا",   
            "currency_english" : "JD",    
        }, 
        {
            "id" : 4,
            "mentor_id" : 1,
            "appointment_id" : 4,
            "status" : PaymentStatus.approved,   
            "amount" : 18.56,   
            "currency_arabic" : "د.ا",   
            "currency_english" : "JD",    
        },
    ]
    )
    
    op.bulk_insert(DB_Mentor_PaymentsـReports.__table__,
    [
        {
            "id" : 1,
            "mentor_id" : 1,
            "payment_id" : 1,   
            "message" : "There is Something wrong",                                                                                      
        },
        {
            "id" : 2,
            "mentor_id" : 1,
            "payment_id" : 2,   
            "message" : "There is Something wrong",                                                                                     
        },     
    ]
    )

    pass


def downgrade() -> None:
    pass
